services:
  db:
    image: postgres:16
    container_name: meeting-room-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meeting_room_booking
    ports:
      - "5432:5432"
    volumes:
      - meeting-room-db:/var/lib/postgresql/data

volumes:
  meeting-room-db:
